// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy7YbZGGggnakkHmkIPe7ACHnKcu4lWHA',
    appId: '1:936659046488:web:233bc32c3fdf2c2f60ba2d',
    messagingSenderId: '936659046488',
    projectId: 'nutrigene-fcb9e',
    authDomain: 'nutrigene-fcb9e.firebaseapp.com',
    storageBucket: 'nutrigene-fcb9e.firebasestorage.app',
    measurementId: 'G-LN0H68YT0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLptWfh-Ef4epP8SQvXsOfJaRWOcWVAA8',
    appId: '1:936659046488:android:99a76a3fbb137a1b60ba2d',
    messagingSenderId: '936659046488',
    projectId: 'nutrigene-fcb9e',
    storageBucket: 'nutrigene-fcb9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQImfueuByj2VnEyuYCqmardoKF03t1qI',
    appId: '1:936659046488:ios:280a9b124176107e60ba2d',
    messagingSenderId: '936659046488',
    projectId: 'nutrigene-fcb9e',
    storageBucket: 'nutrigene-fcb9e.firebasestorage.app',
    iosBundleId: 'com.example.nutritrack',
  );
}
